offset:
  head_pan: 0
  head_tilt: 0
  l_ank_pitch: 0.08726646259971647
  l_ank_roll: 0
  l_el: 0
  l_hip_pitch: -0.1291543646475804
  l_hip_roll: 0
  l_hip_yaw: 0
  l_knee: 0
  l_sho_pitch: 0
  l_sho_roll: 0
  r_ank_pitch: -0.08726646259971647
  r_ank_roll: 0
  r_el: 0
  r_hip_pitch: 0.1291543646475804
  r_hip_roll: 0
  r_hip_yaw: 0
  r_knee: 0
  r_sho_pitch: 0
  r_sho_roll: 0